/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package orm2tg.tg.schema;

import de.uni_koblenz.jgralab.EdgeDirection;

import orm2tg.tg.schema.Folder;
import orm2tg.tg.schema.FolderPart1;
/**
 * FromVertexClass: FolderPart1
 * FromRoleName : 
 * ToVertexClass: Folder
 * ToRoleName : 
 */

public interface FolderPart1HasFolder extends de.uni_koblenz.jgralab.Edge {

	public static final de.uni_koblenz.jgralab.schema.EdgeClass EC = orm2tg.tg.schema.UniquenessConstraint_nestedPrefRefScheme.instance().getGraphClass().getEdgeClass("FolderPart1HasFolder");

	/**
	 * @return the next orm2tg.tg.schema.FolderPart1HasFolder edge in the global edge sequence
	 */
	public orm2tg.tg.schema.FolderPart1HasFolder getNextFolderPart1HasFolderInGraph();

	/**
	 * @return the next edge of class orm2tg.tg.schema.FolderPart1HasFolder at the "this" vertex
	 */
	public orm2tg.tg.schema.FolderPart1HasFolder getNextFolderPart1HasFolderIncidence();

	/**
	 * @return the next edge of class orm2tg.tg.schema.FolderPart1HasFolder at the "this" vertex
	 * @param orientation the orientation of the edge
	 */
	public orm2tg.tg.schema.FolderPart1HasFolder getNextFolderPart1HasFolderIncidence(EdgeDirection orientation);
	public FolderPart1 getAlpha();
	public Folder getOmega();
}
