/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package orm2tg.tg.schema;

import de.uni_koblenz.jgralab.GraphFactory;

public interface UniquenessConstraint_nestedPrefRefSchemeGraphFactory extends GraphFactory {
}
